/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DietUpdateManyWithoutUsersInput } from "./DietUpdateManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { ProgressUpdateManyWithoutUsersInput } from "./ProgressUpdateManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { WorkoutUpdateManyWithoutUsersInput } from "./WorkoutUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: () => DietUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => DietUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => DietUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  diets?: DietUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
    type: () => ProgressUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ProgressUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ProgressUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  progresses?: ProgressUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;

  @ApiProperty({
    required: false,
    type: () => WorkoutUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => WorkoutUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => WorkoutUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  workouts?: WorkoutUpdateManyWithoutUsersInput;
}

export { UserUpdateInput as UserUpdateInput };
