/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DietCreateNestedManyWithoutUsersInput } from "./DietCreateNestedManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { ProgressCreateNestedManyWithoutUsersInput } from "./ProgressCreateNestedManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { WorkoutCreateNestedManyWithoutUsersInput } from "./WorkoutCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => DietCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => DietCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => DietCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  diets?: DietCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    type: () => ProgressCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ProgressCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ProgressCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  progresses?: ProgressCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: false,
    type: () => WorkoutCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => WorkoutCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => WorkoutCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  workouts?: WorkoutCreateNestedManyWithoutUsersInput;
}

export { UserCreateInput as UserCreateInput };
